[package]
name = "idn"
version = "1.0.0"
edition = "2021"
rust-version = "1.81"
description = "Fast, small and simple IDNA implementation"
license = "MIT OR Apache-2.0"
keywords = ["idna", "punycode", "unicode", "dns", "no-std"]
categories = ["encoding", "internationalization", "no-std"]
readme = "../README.md"
include = ["src/**/*.rs", "LICENSE-*"]

[dev-dependencies]
criterion = { version = "0.8", default-features = false }
codspeed-criterion-compat = "5"
idna = "1.1"
idna-0-5 = { package = "idna", version = "0.5" }

[[bench]]
name = "compare"
harness = false

[workspace.lints.rust]
elided_lifetimes_in_paths = "warn"
trivial_numeric_casts = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(coverage,coverage_nightly)"] }
unnameable_types = "warn"
unreachable_pub = "warn"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_qualifications = "warn"

[workspace.lints.clippy]
alloc_instead_of_core = "warn"
cloned_instead_of_copied = "warn"
manual_let_else = "warn"
or_fun_call = "warn"
std_instead_of_core = "warn"
undocumented_unsafe_blocks = "warn"
upper_case_acronyms = "warn"
use_self = "warn"
