//! Checks that `src/tables.rs` is generated from the Unicode Character Database files in `data/`
//!
//! If the generated tables differ from `src/tables.rs`, this overwrites the file and fails, so that
//! running the tests again passes. The data layout is documented in `src/unicode.rs`, which
//! contains the lookup code.

use core::fmt::Write;
use core::hash::Hash;
use core::ops::RangeInclusive;
use std::collections::{BTreeMap, HashMap, HashSet};
use std::fmt;
use std::fs;
use std::path::Path;

#[test]
fn tables_are_up_to_date() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let ucd = Ucd::load(&root.join("data"));

    let mut out = String::new();
    writeln!(
        out,
        "//! Unicode {} data tables, generated by `tests/codegen.rs`\n//!\n//! Do not edit.\n",
        ucd.version
    )
    .unwrap();
    let (major, minor, update) = ucd.version_tuple();
    writeln!(
        out,
        "pub(crate) const UNICODE_VERSION: (u8, u8, u8) = ({major}, {minor}, {update});\n"
    )
    .unwrap();
    writeln!(out, "pub(crate) const SECOND_BITS: u32 = {SECOND_BITS};").unwrap();
    writeln!(out, "pub(crate) const THIRD_BITS: u32 = {THIRD_BITS};\n").unwrap();

    let mapping = Mapping::new(&ucd);
    mapping.trie.write("MAPPING", "u32", &mut out);
    write_array(&mut out, "MAPPING_POOL", "u16", &mapping.pool, |u| {
        format!("0x{u:04x}")
    });

    let mut properties = Vec::with_capacity(CODE_POINTS);
    for cp in 0..CODE_POINTS {
        properties.push(
            u16::from(ucd.bidi_class[cp])
                | u16::from(ucd.joining_type[cp]) << JOINING_TYPE_SHIFT
                | u16::from(ucd.mark[cp]) << MARK_SHIFT,
        );
    }
    Trie::new(&properties).write("PROPERTIES", "u16", &mut out);

    let mut bmp = Vec::new();
    let mut supplementary = Vec::new();
    for (&(first, second), &composite) in &ucd.compositions {
        match (u16::try_from(first), u16::try_from(second)) {
            (Ok(first), Ok(second)) => {
                let composite = u16::try_from(composite).expect("BMP pairs compose to BMP");
                bmp.push((first, second, composite));
            }
            _ => supplementary.push((first, second, composite)),
        }
    }
    write_array(
        &mut out,
        "COMPOSITIONS_BMP",
        "(u16, u16, u16)",
        &bmp,
        |(a, b, c)| format!("(0x{a:04x}, 0x{b:04x}, 0x{c:04x})"),
    );
    write_array(
        &mut out,
        "COMPOSITIONS_SUPPLEMENTARY",
        "(char, char, char)",
        &supplementary,
        |(a, b, c)| format!("('\\u{{{a:x}}}', '\\u{{{b:x}}}', '\\u{{{c:x}}}')"),
    );

    eprintln!(
        "mapping: {} bytes, pool: {} bytes, properties: {} bytes, compositions: {} bytes",
        mapping.trie.size(4),
        mapping.pool.len() * 2,
        Trie::new(&properties).size(2),
        bmp.len() * 6 + supplementary.len() * 12,
    );

    let path = root.join("src/tables.rs");
    if fs::read_to_string(&path).is_ok_and(|current| current == out) {
        return;
    }

    fs::write(&path, out).unwrap();
    panic!("src/tables.rs was out of date and has been regenerated");
}

/// Per-code point mapping entries plus the pool of multi-character mappings
///
/// The pool is encoded in UTF-16. Each entry is a `u32` with the following layout:
///
/// - bits 0..=20: payload (a code point delta, or a pool offset and length in UTF-16 code
///   units)
/// - bits 21..=23: `Kind`
/// - bits 24..=31: the Canonical_Combining_Class of the code point itself
struct Mapping {
    trie: Trie<u32>,
    pool: Vec<u16>,
}

impl Mapping {
    fn new(ucd: &Ucd) -> Self {
        let mut pool = Vec::new();
        let mut interned = HashMap::<Vec<u16>, u32>::new();
        let mut entries = Vec::with_capacity(CODE_POINTS);
        for cp in 0..CODE_POINTS as u32 {
            let (kind, payload) = match ucd.entry(cp, &mut pool, &mut interned) {
                Entry::Keep => (Kind::Keep, 0),
                Entry::Disallowed => (Kind::Disallowed, 0),
                Entry::Ignored => (Kind::Ignored, 0),
                Entry::Single { target, boundary } => {
                    let delta = target.wrapping_sub(cp) & PAYLOAD_MASK;
                    match boundary {
                        true => (Kind::SingleBoundary, delta),
                        false => (Kind::Single, delta),
                    }
                }
                Entry::Pool { offset, len, kind } => {
                    assert!(offset < 1 << POOL_OFFSET_BITS, "pool too large");
                    assert!(len < 1 << (21 - POOL_OFFSET_BITS), "mapping too long");
                    (kind, offset | len << POOL_OFFSET_BITS)
                }
            };

            entries.push(
                payload
                    | (kind as u32) << KIND_SHIFT
                    | u32::from(ucd.ccc[cp as usize]) << CCC_SHIFT,
            );
        }

        Self {
            trie: Trie::new(&entries),
            pool,
        }
    }
}

#[derive(Clone, Copy, Debug)]
enum Entry {
    /// Valid, maps to itself and is a composition boundary (or a Hangul syllable)
    Keep,
    /// Disallowed; maps to U+FFFD REPLACEMENT CHARACTER, which is a composition boundary
    Disallowed,
    /// Ignored; maps to the empty string
    Ignored,
    /// Maps (after decomposition) to a single code point
    Single { target: u32, boundary: bool },
    /// Maps (after decomposition) to a sequence stored in the pool
    Pool { offset: u32, len: u32, kind: Kind },
}

/// Must be kept in sync with `Kind` in `src/unicode.rs`
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Kind {
    Keep = 0,
    Disallowed = 1,
    Ignored = 2,
    SingleBoundary = 3,
    Single = 4,
    PoolComposed = 5,
    PoolBoundary = 6,
    Pool = 7,
}

struct Ucd {
    version: String,
    status: Vec<Status>,
    ccc: Vec<u8>,
    decompositions: HashMap<u32, Vec<u32>>,
    compositions: BTreeMap<(u32, u32), u32>,
    second_elements: HashSet<u32>,
    bidi_class: Vec<u8>,
    joining_type: Vec<u8>,
    mark: Vec<bool>,
}

impl Ucd {
    fn load(dir: &Path) -> Self {
        let read = |name: &str| fs::read_to_string(dir.join(name)).unwrap();

        let idna = read("IdnaMappingTable.txt");
        let version = idna
            .lines()
            .find_map(|line| line.strip_prefix("# Version: "))
            .expect("version header")
            .trim()
            .to_owned();

        let mut status = vec![Status::Disallowed; CODE_POINTS];
        for (range, fields) in records(&idna) {
            let value = match fields[0] {
                "valid" => Status::Valid,
                "deviation" => Status::Deviation,
                "ignored" => Status::Ignored,
                "disallowed" => Status::Disallowed,
                "mapped" => Status::Mapped(code_points(fields[1])),
                other => panic!("unknown IDNA status {other:?}"),
            };
            for cp in range {
                status[cp as usize] = value.clone();
            }
        }

        let ccc = property(&read("DerivedCombiningClass.txt"), |value| match value {
            "Not_Reordered" => 0,
            _ => value.parse().expect("numeric combining class"),
        });

        let mut decompositions = HashMap::new();
        for line in read("UnicodeData.txt").lines() {
            let fields = line.split(';').collect::<Vec<_>>();
            if fields[5].is_empty() || fields[5].starts_with('<') {
                continue;
            }
            decompositions.insert(
                u32::from_str_radix(fields[0], 16).unwrap(),
                code_points(fields[5]),
            );
        }

        let mut exclusions = HashSet::new();
        for (range, fields) in records(&read("DerivedNormalizationProps.txt")) {
            if fields[0] == "Full_Composition_Exclusion" {
                exclusions.extend(range);
            }
        }

        let mut compositions = BTreeMap::new();
        let mut second_elements = HashSet::new();
        for (&composite, decomposed) in &decompositions {
            if decomposed.len() != 2 || exclusions.contains(&composite) {
                continue;
            }
            compositions.insert((decomposed[0], decomposed[1]), composite);
            second_elements.insert(decomposed[1]);
        }
        second_elements.extend(HANGUL_V_BASE..HANGUL_V_BASE + HANGUL_V_COUNT);
        second_elements.extend(HANGUL_T_BASE + 1..HANGUL_T_BASE + HANGUL_T_COUNT);

        let bidi_class = property(&read("DerivedBidiClass.txt"), |value| {
            BIDI_CLASSES
                .iter()
                .position(|&(short, long)| value == short || value == long)
                .unwrap_or_else(|| panic!("unknown bidi class {value:?}")) as u8
        });
        let joining_type = property(&read("DerivedJoiningType.txt"), |value| {
            JOINING_TYPES
                .iter()
                .position(|&(short, long)| value == short || value == long)
                .unwrap_or_else(|| panic!("unknown joining type {value:?}")) as u8
        });
        let mark = property(&read("DerivedGeneralCategory.txt"), |value| {
            matches!(value, "Mn" | "Mc" | "Me")
        });

        Self {
            version,
            status,
            ccc,
            decompositions,
            compositions,
            second_elements,
            bidi_class,
            joining_type,
            mark,
        }
    }

    fn entry(&self, cp: u32, pool: &mut Vec<u16>, interned: &mut HashMap<Vec<u16>, u32>) -> Entry {
        let mapped = match &self.status[cp as usize] {
            Status::Disallowed => return Entry::Disallowed,
            Status::Ignored => return Entry::Ignored,
            Status::Valid | Status::Deviation => vec![cp],
            Status::Mapped(mapped) => mapped.clone(),
        };

        let decomposed = self.nfd(&mapped);
        let boundary = self.is_boundary(decomposed[0]);
        if is_hangul_syllable(cp) {
            assert_eq!(mapped, [cp]);
            return Entry::Keep;
        }

        if decomposed == [cp] && boundary {
            return Entry::Keep;
        }

        if let [target] = decomposed[..] {
            return Entry::Single { target, boundary };
        }

        let composed = self.nfc(&decomposed);
        let (kind, key) = match (boundary, &composed[..]) {
            (true, &[single]) => {
                let mut key = vec![single];
                key.extend(&decomposed);
                (Kind::PoolComposed, key)
            }
            (true, _) => (Kind::PoolBoundary, decomposed.clone()),
            (false, _) => (Kind::Pool, decomposed.clone()),
        };

        let key = utf16(&key);
        let offset = *interned.entry(key.clone()).or_insert_with(|| {
            let offset = pool.len() as u32;
            pool.extend(&key);
            offset
        });

        Entry::Pool {
            offset,
            len: utf16(&decomposed).len() as u32,
            kind,
        }
    }

    /// Whether `cp` can never interact with any preceding code point during composition
    fn is_boundary(&self, cp: u32) -> bool {
        self.ccc[cp as usize] == 0 && !self.second_elements.contains(&cp)
    }

    /// Canonical Composition Algorithm (UAX #15, section 3.11) on a decomposed string
    fn nfc(&self, decomposed: &[u32]) -> Vec<u32> {
        let mut out = Vec::<u32>::new();
        let mut starter = None;
        let mut last_ccc = None;
        for &cp in decomposed {
            let ccc = self.ccc[cp as usize];
            if let Some(index) = starter {
                let unblocked = match last_ccc {
                    None => true,
                    Some(last) => last != 0 && last < ccc,
                };
                if unblocked {
                    if let Some(composite) = self.compose(out[index], cp) {
                        out[index] = composite;
                        continue;
                    }
                }
            }

            match ccc {
                0 => {
                    starter = Some(out.len());
                    last_ccc = None;
                }
                _ => last_ccc = Some(ccc),
            }
            out.push(cp);
        }

        out
    }

    fn compose(&self, first: u32, second: u32) -> Option<u32> {
        if (HANGUL_L_BASE..HANGUL_L_BASE + HANGUL_L_COUNT).contains(&first)
            && (HANGUL_V_BASE..HANGUL_V_BASE + HANGUL_V_COUNT).contains(&second)
        {
            let lv = (first - HANGUL_L_BASE) * HANGUL_N_COUNT
                + (second - HANGUL_V_BASE) * HANGUL_T_COUNT;
            return Some(HANGUL_S_BASE + lv);
        }

        if is_hangul_syllable(first)
            && (first - HANGUL_S_BASE) % HANGUL_T_COUNT == 0
            && (HANGUL_T_BASE + 1..HANGUL_T_BASE + HANGUL_T_COUNT).contains(&second)
        {
            return Some(first + second - HANGUL_T_BASE);
        }

        self.compositions.get(&(first, second)).copied()
    }

    /// Full canonical decomposition followed by the Canonical Ordering Algorithm
    fn nfd(&self, input: &[u32]) -> Vec<u32> {
        let mut out = Vec::new();
        for &cp in input {
            self.decompose(cp, &mut out);
        }

        let mut start = 0;
        while start < out.len() {
            if self.ccc[out[start] as usize] == 0 {
                start += 1;
                continue;
            }

            let mut end = start;
            while end < out.len() && self.ccc[out[end] as usize] != 0 {
                end += 1;
            }

            out[start..end].sort_by_key(|&cp| self.ccc[cp as usize]);
            start = end;
        }

        out
    }

    fn decompose(&self, cp: u32, out: &mut Vec<u32>) {
        if is_hangul_syllable(cp) {
            let index = cp - HANGUL_S_BASE;
            out.push(HANGUL_L_BASE + index / HANGUL_N_COUNT);
            out.push(HANGUL_V_BASE + (index % HANGUL_N_COUNT) / HANGUL_T_COUNT);
            if index % HANGUL_T_COUNT != 0 {
                out.push(HANGUL_T_BASE + index % HANGUL_T_COUNT);
            }
            return;
        }

        match self.decompositions.get(&cp) {
            Some(decomposed) => {
                for &cp in decomposed {
                    self.decompose(cp, out);
                }
            }
            None => out.push(cp),
        }
    }

    fn version_tuple(&self) -> (u8, u8, u8) {
        let mut parts = self
            .version
            .split('.')
            .map(|part| part.parse::<u8>().unwrap());
        (
            parts.next().unwrap(),
            parts.next().unwrap(),
            parts.next().unwrap(),
        )
    }
}

#[derive(Clone, Debug)]
enum Status {
    Valid,
    Deviation,
    Ignored,
    Mapped(Vec<u32>),
    Disallowed,
}

/// Parses a UCD file with a single property value per code point range
///
/// `@missing` lines are applied in order before the explicit assignments.
fn property<T: Clone + Default>(data: &str, parse: impl Fn(&str) -> T) -> Vec<T> {
    let mut values = vec![T::default(); CODE_POINTS];
    for line in data.lines() {
        let Some(missing) = line.strip_prefix("# @missing: ") else {
            continue;
        };
        let (range, value) = missing.split_once(';').unwrap();
        let value = parse(value.trim());
        for cp in range_of(range.trim()) {
            values[cp as usize] = value.clone();
        }
    }

    for (range, fields) in records(data) {
        let value = parse(fields[0]);
        for cp in range {
            values[cp as usize] = value.clone();
        }
    }

    values
}

/// Iterates over the non-comment records in a UCD file as (range, fields) pairs
fn records(data: &str) -> impl Iterator<Item = (RangeInclusive<u32>, Vec<&str>)> {
    data.lines().filter_map(|line| {
        let line = line.split('#').next().unwrap().trim();
        if line.is_empty() {
            return None;
        }

        let mut fields = line.split(';').map(str::trim);
        let range = range_of(fields.next().unwrap());
        Some((range, fields.collect()))
    })
}

fn range_of(s: &str) -> RangeInclusive<u32> {
    match s.split_once("..") {
        Some((start, end)) => {
            u32::from_str_radix(start, 16).unwrap()..=u32::from_str_radix(end, 16).unwrap()
        }
        None => {
            let cp = u32::from_str_radix(s, 16).unwrap();
            cp..=cp
        }
    }
}

fn code_points(s: &str) -> Vec<u32> {
    s.split_whitespace()
        .map(|cp| u32::from_str_radix(cp, 16).unwrap())
        .collect()
}

fn utf16(code_points: &[u32]) -> Vec<u16> {
    let mut units = Vec::new();
    for &cp in code_points {
        let c = char::from_u32(cp).unwrap();
        units.extend_from_slice(c.encode_utf16(&mut [0; 2]));
    }
    units
}

fn is_hangul_syllable(cp: u32) -> bool {
    (HANGUL_S_BASE..HANGUL_S_BASE + HANGUL_S_COUNT).contains(&cp)
}

/// A three-level trie mapping every code point to a value
///
/// The first level is indexed by `cp >> (SECOND_BITS + THIRD_BITS)` and yields a second-level
/// block number. Second-level blocks are indexed by the next `SECOND_BITS` bits of the code point
/// and yield the offsets of third-level blocks. Third-level blocks are indexed by the low
/// `THIRD_BITS` bits and contain the values. Identical blocks at each level are shared, and
/// third-level blocks may overlap (see [`place()`]).
struct Trie<T> {
    first: Vec<u16>,
    second: Vec<u16>,
    third: Vec<T>,
}

impl<T: Copy + Eq + Hash + fmt::Display> Trie<T> {
    fn new(values: &[T]) -> Self {
        assert_eq!(values.len(), CODE_POINTS);
        let mut third = Vec::new();
        let mut third_blocks = HashMap::<&[T], u16>::new();
        let mut second_ids = Vec::new();
        for block in values.chunks(1 << THIRD_BITS) {
            let offset = *third_blocks
                .entry(block)
                .or_insert_with(|| place(&mut third, block));
            second_ids.push(offset);
        }

        let mut second = Vec::new();
        let mut second_blocks = HashMap::<&[u16], u16>::new();
        let mut first = Vec::new();
        for block in second_ids.chunks(1 << SECOND_BITS) {
            let next = second_blocks.len() as u16;
            let id = *second_blocks.entry(block).or_insert_with(|| {
                second.extend_from_slice(block);
                next
            });
            first.push(id);
        }

        Self {
            first,
            second,
            third,
        }
    }

    fn write(&self, name: &str, ty: &str, out: &mut String) {
        let first_ty = match self.first_width() {
            1 => "u8",
            _ => "u16",
        };
        write_array(out, &format!("{name}_FIRST"), first_ty, &self.first, |v| {
            v.to_string()
        });
        write_array(out, &format!("{name}_SECOND"), "u16", &self.second, |v| {
            v.to_string()
        });
        write_array(out, &format!("{name}_THIRD"), ty, &self.third, |v| {
            v.to_string()
        });
    }

    fn size(&self, value_size: usize) -> usize {
        self.first.len() * self.first_width()
            + self.second.len() * 2
            + self.third.len() * value_size
    }

    fn first_width(&self) -> usize {
        match self.first.iter().max() {
            Some(&max) if max <= u16::from(u8::MAX) => 1,
            _ => 2,
        }
    }
}

/// Stores `block` in `data`, returning its offset
///
/// To save space, this reuses an existing occurrence of `block`, or overlaps it with the end of
/// `data` as far as possible.
fn place<T: Copy + Eq>(data: &mut Vec<T>, block: &[T]) -> u16 {
    let start = match data.windows(block.len()).position(|window| window == block) {
        Some(start) => start,
        None => {
            let overlap = (1..block.len())
                .rev()
                .find(|&len| data.ends_with(&block[..len]))
                .unwrap_or(0);
            data.extend_from_slice(&block[overlap..]);
            data.len() - block.len()
        }
    };

    u16::try_from(start).expect("third-level offsets fit in a u16")
}

fn write_array<T>(
    out: &mut String,
    name: &str,
    ty: &str,
    values: &[T],
    fmt: impl Fn(&T) -> String,
) {
    writeln!(
        out,
        "pub(crate) static {name}: [{ty}; {}] = [",
        values.len()
    )
    .unwrap();
    let mut line = String::new();
    for value in values {
        let item = fmt(value);
        if line.len() + item.len() + 2 > 96 {
            writeln!(out, "    {}", line.trim_end()).unwrap();
            line.clear();
        }
        line.push_str(&item);
        line.push_str(", ");
    }
    if !line.is_empty() {
        writeln!(out, "    {}", line.trim_end()).unwrap();
    }
    writeln!(out, "];\n").unwrap();
}

/// Must be kept in sync with `BidiClass` in `src/unicode.rs`
const BIDI_CLASSES: [(&str, &str); 23] = [
    ("L", "Left_To_Right"),
    ("R", "Right_To_Left"),
    ("AL", "Arabic_Letter"),
    ("EN", "European_Number"),
    ("ES", "European_Separator"),
    ("ET", "European_Terminator"),
    ("AN", "Arabic_Number"),
    ("CS", "Common_Separator"),
    ("NSM", "Nonspacing_Mark"),
    ("BN", "Boundary_Neutral"),
    ("B", "Paragraph_Separator"),
    ("S", "Segment_Separator"),
    ("WS", "White_Space"),
    ("ON", "Other_Neutral"),
    ("LRE", "Left_To_Right_Embedding"),
    ("LRO", "Left_To_Right_Override"),
    ("RLE", "Right_To_Left_Embedding"),
    ("RLO", "Right_To_Left_Override"),
    ("PDF", "Pop_Directional_Format"),
    ("LRI", "Left_To_Right_Isolate"),
    ("RLI", "Right_To_Left_Isolate"),
    ("FSI", "First_Strong_Isolate"),
    ("PDI", "Pop_Directional_Isolate"),
];

/// Must be kept in sync with `JoiningType` in `src/unicode.rs`
const JOINING_TYPES: [(&str, &str); 6] = [
    ("U", "Non_Joining"),
    ("C", "Join_Causing"),
    ("D", "Dual_Joining"),
    ("L", "Left_Joining"),
    ("R", "Right_Joining"),
    ("T", "Transparent"),
];

const CODE_POINTS: usize = 0x11_0000;
const THIRD_BITS: u32 = 3;
const SECOND_BITS: u32 = 5;

const PAYLOAD_MASK: u32 = (1 << 21) - 1;
const POOL_OFFSET_BITS: u32 = 16;
const KIND_SHIFT: u32 = 21;
const CCC_SHIFT: u32 = 24;

const JOINING_TYPE_SHIFT: u32 = 5;
const MARK_SHIFT: u32 = 8;

const HANGUL_S_BASE: u32 = 0xac00;
const HANGUL_L_BASE: u32 = 0x1100;
const HANGUL_V_BASE: u32 = 0x1161;
const HANGUL_T_BASE: u32 = 0x11a7;
const HANGUL_L_COUNT: u32 = 19;
const HANGUL_V_COUNT: u32 = 21;
const HANGUL_T_COUNT: u32 = 28;
const HANGUL_N_COUNT: u32 = HANGUL_V_COUNT * HANGUL_T_COUNT;
const HANGUL_S_COUNT: u32 = HANGUL_L_COUNT * HANGUL_N_COUNT;
